name: build
on:
  push:
    branches:
      - master # 这里表示push到main分支就会触发流程
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      # 这是github官方的一个action，用于clone该仓库的源码到工作流中，
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm install  # 安装依赖
          npm run build  # 执行打包

      # 连接到ssh，并且做一个拷贝操作的action
      - name: Deploy 🚀
        uses: AEnterprise/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.PRIVATE_KEY }} # use pre-configured secret (the private key)
          ARGS: -avz --delete # must have this variable
          SERVER_PORT: "22" # SSH port
          FOLDER: ./dist/*
          SERVER_IP: ${{ secrets.DR_HOST }} # use pre-configured ssh_host value (e.g., IP or domain.com）
          USERNAME: ${{ secrets.DR_USER }} # use pre-configured ssh_username value
          SERVER_DESTINATION: /home/www/blogAdmin/ # put your repo files on this directory of the remote server



